kind: pipeline
type: docker
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: testing1
  pull: always
  image: golang:1.12-alpine
  commands:
  - echo "test1"
  - echo "test2"
  when:
    branch:
    - master

trigger:
  branch:
  - master
  event:
  - push
  